FROM ubuntu:24.04
ARG VERSION_URL=0
ARG VERSION_HASH=0
RUN ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime \
    && DEBIAN_FRONTEND=noninteractive apt-get update \
    && apt-get install -y -q --no-install-recommends \
	python3.12 \
	python3.12-venv \
    && rm -r /var/lib/apt/lists/* /var/cache/*
WORKDIR /opt/StaticJinjaPlus
ADD --checksum=sha256:${VERSION_HASH} ${VERSION_URL} /tmp/app.tar.gz
RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /opt/StaticJinjaPlus && rm /tmp/app.tar.gz
RUN python3.12 -m venv venv && venv/bin/pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["venv/bin/python", "main.py"]
CMD ["--srcpath=data/templates/", "--outpath=data/build/"]
