FROM python:3.12.8-slim
ARG VERSION_URL=0
ARG VERSION_HASH=0
WORKDIR /opt/StaticJinjaPlus
ADD --checksum=sha256:${VERSION_HASH} ${VERSION_URL} /tmp/app.tar.gz
RUN tar xzf /tmp/app.tar.gz --strip-components=1 -C /opt/StaticJinjaPlus && rm /tmp/app.tar.gz
RUN pip install --no-cache-dir -r requirements.txt
ENTRYPOINT ["python3", "main.py"]
CMD ["--srcpath=data/templates/", "--outpath=data/build/"]
